### ISSUE TITLE
Aggregate Signal calls get() with subscribe

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/pcdsdevices#370]
While testing LUCID, I bumped into a device that when we subscribe it calls `.get()` and that causes the signals to wait for connection.
The issue was with the `PulsePicker` device that seems to have an `AggregateSignal`.
See: https://github.com/pcdshub/pcdsdevices/blob/84cd02f9a2d2f2bd5f57c029e1e009cee2a73a18/pcdsdevices/signal.py#L97
and
https://github.com/pcdshub/pcdsdevices/blob/dbe80402de03fc2beb11b626303f312757cf8749/pcdsdevices/state.py#L297

`PulsePicker` -> `InOutPVStatePositioner` -> `PVStatePositioner` (Component state is a `PVStateSignal`)

## Expected Behavior

Subscribing to the device does not cause a wait if device is disconnected

## Current Behavior

Exception is raised if device is disconnected
```
Traceback (most recent call last):
  File "/Users/slepicka/sandbox/git-pcdshub/typhon-git/typhos/plugins/core.py", line 214, in add_connection
    super().add_connection(channel)
  File "/Users/slepicka/sandbox/git-slaclab/pydm-git/pydm/data_plugins/plugin.py", line 175, in add_connection
    self.protocol)
  File "/Users/slepicka/sandbox/git-pcdshub/typhon-git/typhos/plugins/core.py", line 69, in __init__
    event_type=self.signal.SUB_VALUE)
  File "/Users/slepicka/sandbox/git-pcdshub/pcdsdevices-git/pcdsdevices/signal.py", line 97, in subscribe
    self.get()  # Ensure we have a full cache
  File "/Users/slepicka/sandbox/git-pcdshub/pcdsdevices-git/pcdsdevices/signal.py", line 79, in get
    self._cache[signal] = signal.get(**kwargs)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/signal.py", line 959, in get
    self._read_pv, timeout, connection_timeout, as_string, form)
  File "/Users/slepicka/sandbox/git-slepicka/ophyd-git/ophyd/signal.py", line 915, in _get_with_timeout
    f"within {connection_timeout:.2} sec") from err
ophyd.signal.ConnectionTimeoutError: Failed to connect to MFX:DIA:MMS:07:READ_DF within 1.0 sec
```

## Possible Solution

Maybe add a `if self.connected` before calling `self.get` at https://github.com/pcdshub/pcdsdevices/blob/84cd02f9a2d2f2bd5f57c029e1e009cee2a73a18/pcdsdevices/signal.py#L97 but I am not sure.

**Comment by ZLLentz** [comment]
Might also be solvable with initializing the value in a callback instead of by getting it "right now". Definitely needs to be fixed.
