### ISSUE TITLE
Error message from inout device.

### ISSUE THREAD

**Issue by hhslepicka** [pcdshub/pcdsdevices#406]
## Expected Behavior
No error message.

## Current Behavior
When opening lucid LFE I got the error messages below.
This can be reproduced if you ssh into one of the PCDS machines and type lfe.
All packages are using master.

```python
[2020-03-31 14:20:34,112] [ERROR   ] - Subscription meta callback exception (EpicsSignal(read_pv='IM1L0:XTES:MMS:STATE:GET_RBV', name='im1l0_y_states_state', parent='im1l0_y_states', value=4, timestamp=1585229929.895677, auto_monitor=False, string=False, write_pv='IM1L0:XTES:MMS:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 471, in inner
    cb(*args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _late_state_init
    self._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 544, in _state_init
    super()._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 73, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 124, in _extend_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2020-03-31 14:20:34,421] [ERROR   ] - Subscription meta callback exception (EpicsSignal(read_pv='IM1L1:PPM:MMS:STATE:GET_RBV', name='im1l1_y_states_state', parent='im1l1_y_states', value=3, timestamp=1584138839.406217, auto_monitor=False, string=False, write_pv='IM1L1:PPM:MMS:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 471, in inner
    cb(*args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _late_state_init
    self._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 544, in _state_init
    super()._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 73, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 124, in _extend_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2020-03-31 14:20:34,696] [ERROR   ] - Subscription meta callback exception (EpicsSignal(read_pv='IM2L0:XTES:MMS:STATE:GET_RBV', name='im2l0_y_states_state', parent='im2l0_y_states', value=4, timestamp=1584138839.406217, auto_monitor=False, string=False, write_pv='IM2L0:XTES:MMS:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 471, in inner
    cb(*args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _late_state_init
    self._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 544, in _state_init
    super()._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 73, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 124, in _extend_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2020-03-31 14:20:34,988] [ERROR   ] - Subscription meta callback exception (EpicsSignal(read_pv='IM3L0:PPM:MMS:STATE:GET_RBV', name='im3l0_y_states_state', parent='im3l0_y_states', value=1, timestamp=1584138839.406217, auto_monitor=False, string=False, write_pv='IM3L0:PPM:MMS:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 471, in inner
    cb(*args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _late_state_init
    self._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 544, in _state_init
    super()._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 73, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 124, in _extend_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2020-03-31 14:20:35,252] [ERROR   ] - Subscription meta callback exception (EpicsSignal(read_pv='IM4L0:XTES:MMS:STATE:GET_RBV', name='im4l0_y_states_state', parent='im4l0_y_states', value=4, timestamp=1584138839.406217, auto_monitor=False, string=False, write_pv='IM4L0:XTES:MMS:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 471, in inner
    cb(*args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _late_state_init
    self._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 544, in _state_init
    super()._state_init()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1607, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 73, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 124, in _extend_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
```

**Comment by ZLLentz** [comment]
Probably related to https://github.com/pcdshub/pcdsdevices/pull/404

**Comment by hhslepicka** [comment]
Wouldn't it be awesome if we were able to nuke #404 just so it goes to a 404 not found? 🤣

**Comment by ZLLentz** [comment]
The standard in/out states in the motion library have "OUT" on their enum. So most things will be using "OUT". The special ones I made for the PPM and the XPIM use "Out" instead. I will change them all to "OUT" to increase consistency with states that came before these new systems.

Leaving this issue open because:
1. I can't do new deployments right now (we're stuck with Out for a bit)
2. I think pcdsdevices should react better to stuff like this

**Comment by hhslepicka** [comment]
There is also no "IN" state but can't we switch the logic at pcdsdevices to be case insensitive? The list is small so it wouldn't be a big issue to loop over it for a case insensitive search, right?

**Comment by ZLLentz** [comment]
I think case insensitivity is a very practical solution, since no device will have both an "Out" and an "OUT" state or a "Target1" and a "TaRgEt1" state. I also think the states classes should do some checking of these various states parameters and show clear warnings instead of tracebacks if there are inconsistencies between states_list, in_states, out_states, etc.
