### ISSUE TITLE
Ophyd utility thread scheduling can happen prior to thread initialization?

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#661]
https://github.com/pcdshub/pcdsdevices/blob/69355c881fd8c44db9830f6d19d244688481fd3a/pcdsdevices/utils.py#L203

````
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/utils.py", line 203, in schedule
    context.event_thread.queue.put((func, args, kwargs))
AttributeError: 'NoneType' object has no attribute 'queue'
```

Seen while running `kfe` on `kfe-console`. Unclear which device this is coming from.

**Comment by ZLLentz** [comment]
Ah! Hugo had a dev fix for this that never got merged (or committed?), a quick `if context.event_thread is not None:`

It didn't seem to cause any issues... maybe it's time to PR it

**Comment by hhslepicka** [comment]
Yes! I put that into my pcdsdevices but it ended up never being committed. Sorry about that.
I can put the PR today.
