### ISSUE TITLE
Ensure custom attenuator screens for AT2K2, AT1K4, etc. load by default

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#932]
## Expected Behavior
* Loading AT2K2 in typhos, one should see the custom screens we've made by default

## Current Behavior
* Currently, you have to click on `detailed_tree` to get the correct screen
* The default screen is nearly useless and confuses users

## Possible Solution
Rename screens so that typhos's internal mechanism picks the right one, no matter the display type?
Or make a simpler embedded screen?

## Steps to Reproduce (for bugs)
Load attenuator screen in LUCID

## Context
Users indicate this may have changed at some point, but I'm not sure that's the case as I don't think the method has changed in typhos or here.

## Your Environment
pcds-5.1.1

**Comment by klauer** [comment]
cc @jyotiphy - the linked PR changes are currently in dev typhos right now and should hopefully address the issue.

**Comment by jyotiphy** [comment]
@klauer If I open "rix" lucid screen from say rix-daq machine, there are lot of error printouts related to AT2K2 (see below). 

*****
rix-daq:~> rix
rix-daq:~> [2022-02-02 10:52:35,068] [INFO    ] - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-02-02 10:52:35,068] [INFO    ] - NumExpr defaulting to 8 threads.
[2022-02-02 10:52:36,906] [WARNING ] - Can not enforce type to match attribute calculator_prefix
[2022-02-02 10:52:37,008] [ERROR   ] - Subscription meta callback exception (EpicsSignalEditMD(read_pv='AL1K2:L2SI:MMS:STATE:GET_RBV', name='al1k2_mirror_state', parent='al1k2_mirror', value=1, timestamp=1643557351.008343, auto_monitor=False, string=False, write_pv='AL1K2:L2SI:MMS:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 118, in _late_state_init
    self._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 69, in _state_init
    super()._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _state_init
    self.states_enum = self._create_states_enum()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 309, in _create_states_enum
    raise ValueError(('Bad states definition! Inconsistency in '
ValueError: Bad states definition! Inconsistency in states_list ['Unknown', 'Invalid', 'Invalid'] or _states_alias {}
[2022-02-02 10:52:37,738] [ERROR   ] - Subscription meta callback exception (EpicsSignalEditMD(read_pv='AT2K2:L2SI:MMS:01:STATE:GET_RBV', name='at2k2_blade_01_state_state', parent='at2k2_blade_01_state', value=1, timestamp=1643556342.978623, auto_monitor=False, string=False, write_pv='AT2K2:L2SI:MMS:01:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 118, in _late_state_init
    self._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 76, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 138, in _extend_trans_enum
    self._update_trans_enum(state, default)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 141, in _update_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2022-02-02 10:52:37,743] [ERROR   ] - Subscription meta callback exception (EpicsSignalEditMD(read_pv='AT2K2:L2SI:MMS:02:STATE:GET_RBV', name='at2k2_blade_02_state_state', parent='at2k2_blade_02_state', value=1, timestamp=1643580813.865841, auto_monitor=False, string=False, write_pv='AT2K2:L2SI:MMS:02:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 118, in _late_state_init
    self._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 76, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 138, in _extend_trans_enum
    self._update_trans_enum(state, default)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 141, in _update_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2022-02-02 10:52:37,787] [ERROR   ] - Subscription meta callback exception (EpicsSignalEditMD(read_pv='AT2K2:L2SI:MMS:03:STATE:GET_RBV', name='at2k2_blade_03_state_state', parent='at2k2_blade_03_state', value=1, timestamp=1642494584.459388, auto_monitor=False, string=False, write_pv='AT2K2:L2SI:MMS:03:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 118, in _late_state_init
    self._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 76, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 138, in _extend_trans_enum
    self._update_trans_enum(state, default)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 141, in _update_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2022-02-02 10:52:38,297] [ERROR   ] - Subscription meta callback exception (EpicsSignalEditMD(read_pv='AT2K2:L2SI:MMS:04:STATE:GET_RBV', name='at2k2_blade_04_state_state', parent='at2k2_blade_04_state', value=1, timestamp=1642494584.459388, auto_monitor=False, string=False, write_pv='AT2K2:L2SI:MMS:04:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 118, in _late_state_init
    self._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 76, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 138, in _extend_trans_enum
    self._update_trans_enum(state, default)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 141, in _update_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
[2022-02-02 10:52:38,737] [ERROR   ] - Error in lightpath update callback for at2k2_blade_01.
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 256, in get_state
    return self.states_enum[value]
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'OUT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 259, in get_state
    return self.states_enum(value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'OUT' is not a valid SXRLadderAttenuatorStatesStates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1559, in _update_lightpath
    self._set_lightpath_states(self._lightpath_values)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1620, in _set_lightpath_states
    out_check.append(obj.check_removed(kwarg_dct['value']))
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 94, in check_removed
    return self._pos_in_list(self.out_states, check_state=state)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 150, in _pos_in_list
    if current_state == self.get_state(state):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 265, in get_state
    raise ValueError(err.format(value, self.name, enum_names,
ValueError: OUT is not a valid state for at2k2_blade_01_state. Valid state names are: ['Unknown', 'Out', 'Filter 1', 'Filter 2', 'Filter 3', 'Filter 4', '(5) 11.5 um Al', '(6) 6.18 um Al', '(7) 2.85 um Al', '(8) 1.52 um Al'], and their corresponding values are [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
[2022-02-02 10:52:38,742] [ERROR   ] - Error in lightpath update callback for at2k2_blade_02.
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 256, in get_state
    return self.states_enum[value]
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'OUT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 259, in get_state
    return self.states_enum(value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'OUT' is not a valid SXRLadderAttenuatorStatesStates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1559, in _update_lightpath
    self._set_lightpath_states(self._lightpath_values)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1620, in _set_lightpath_states
    out_check.append(obj.check_removed(kwarg_dct['value']))
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 94, in check_removed
    return self._pos_in_list(self.out_states, check_state=state)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 150, in _pos_in_list
    if current_state == self.get_state(state):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 265, in get_state
    raise ValueError(err.format(value, self.name, enum_names,
ValueError: OUT is not a valid state for at2k2_blade_02_state. Valid state names are: ['Unknown', 'Out', 'Filter 1', 'Filter 2', 'Filter 3', 'Filter 4', '(5) 6.18 um Al', '(6) 2.85 um Al', '(7) 1.52 um Al', '(8) 0.78 um Al'], and their corresponding values are [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
[2022-02-02 10:52:38,745] [ERROR   ] - Error in lightpath update callback for at2k2_blade_03.
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 256, in get_state
    return self.states_enum[value]
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'OUT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 259, in get_state
    return self.states_enum(value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'OUT' is not a valid SXRLadderAttenuatorStatesStates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1559, in _update_lightpath
    self._set_lightpath_states(self._lightpath_values)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1620, in _set_lightpath_states
    out_check.append(obj.check_removed(kwarg_dct['value']))
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 94, in check_removed
    return self._pos_in_list(self.out_states, check_state=state)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 150, in _pos_in_list
    if current_state == self.get_state(state):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 265, in get_state
    raise ValueError(err.format(value, self.name, enum_names,
ValueError: OUT is not a valid state for at2k2_blade_03_state. Valid state names are: ['Unknown', 'Out', 'Filter 1', 'Filter 2', 'Filter 3', 'Filter 4', '(5) 2.85 um Al', '(6) 1.52 um Al', '(7) 0.78 um Al', '(8) 0.39 um Al'], and their corresponding values are [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
[2022-02-02 10:52:38,805] [ERROR   ] - Error in lightpath update callback for at2k2_blade_04.
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 256, in get_state
    return self.states_enum[value]
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: 'OUT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 259, in get_state
    return self.states_enum(value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/cds/group/pcds/pyps/conda/py39/envs/dev/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'OUT' is not a valid SXRLadderAttenuatorStatesStates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1559, in _update_lightpath
    self._set_lightpath_states(self._lightpath_values)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/interface.py", line 1620, in _set_lightpath_states
    out_check.append(obj.check_removed(kwarg_dct['value']))
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 94, in check_removed
    return self._pos_in_list(self.out_states, check_state=state)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 150, in _pos_in_list
    if current_state == self.get_state(state):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 265, in get_state
    raise ValueError(err.format(value, self.name, enum_names,
ValueError: OUT is not a valid state for at2k2_blade_04_state. Valid state names are: ['Unknown', 'Out', 'Filter 1', 'Filter 2', 'Filter 3', 'Filter 4', '(5) 1.52 um Al', '(6) 0.78 um Al', '(7) 0.39 um Al', '(8) 0.20 um Al'], and their corresponding values are [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].
[2022-02-02 10:52:39,800] [ERROR   ] - Subscription meta callback exception (EpicsSignalEditMD(read_pv='SL1K2:EXIT:YAG:STATE:GET_RBV', name='sl1k2_target_state', parent='sl1k2_target', value=1, timestamp=1643704498.28547, auto_monitor=False, string=False, write_pv='SL1K2:EXIT:YAG:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 118, in _late_state_init
    self._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/inout.py", line 69, in _state_init
    super()._state_init()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 108, in _state_init
    self.states_enum = self._create_states_enum()
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/state.py", line 309, in _create_states_enum
    raise ValueError(('Bad states definition! Inconsistency in '
ValueError: Bad states definition! Inconsistency in states_list ['Unknown', 'OUT', 'YAG1', 'YAG2', 'Invalid', 'Invalid', 'Invalid', 'Invalid', 'Invalid', 'Invalid'] or _states_alias {}

**Comment by klauer** [comment]
Thanks, @jyotiphy! We spent a few hours yesterday going over the best way to fix all those errors you reported above. We should have something this afternoon for you once we get out of our entire morning of meetings...
