### ISSUE TITLE
EpicsSignalEditMD still has initialization (?) issues (wrt `.log`)

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#978]
## Behavior
`EpicsSignalEditMD` can throw these errors in typhos:

```python
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/signal.py", line 979, in _enum_string_updated
    self.log.debug(
AttributeError: 'EpicsSignalEditMD' object has no attribute 'log'
```

Related to my changes in #963 assuredly

Ripple effect from the full traceback here:
<details>

```python
[2022-03-24 09:23:22,347] [ERROR   ] - Subscription value callback exception (PytmcSignalRO(read_pv='PF1K0:WFS:MMS:STATE:06:NAME_RBV', name='pf1k0_target_config_state06_state_name', parent='pf1k0_target_config_state06', value='TARGET5', timestamp=1648139001.923994, auto_monitor=False, string=True))
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'target'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'state'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/cds/group/pcds/pyps/apps/dev/pythonpath/pcdsdevices/signal.py", line 979, in _enum_string_updated
    self.log.debug(
AttributeError: 'EpicsSignalEditMD' object has no attribute 'log'
```
</details>

## Possible Solution
Ensure `.log` and other vital attributes are appropriately setup

## Steps to Reproduce (for bugs)
Load `kfe` screens

## Context
Mike E showed these tracebacks in his terminal while debugging a typhos issue

## Your Environment
pcds-dev

**Comment by klauer** [comment]
I think we should address this before tagging. Will look into it in a bit unless someone gets there before me.
